# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/       
VERSION: "1.0.4" # Internal use only

# Choose your transfer type:
# "external" will use an IP address and port to move players between SERVERS
# "internal" will use your preset command string to move players between WORLDS
# "hybrid" will include both transfer types
Transfer-Type: "hybrid"

# This is the command string that will be used to transfer players between WORLDS
# Don't worry about this if you're only using the EXTERNAL transfer type
# Use '{player}' for the player's name
# Use '{world}' for the world name
World-CMD: "multiworld tp {world} {player}"

# This is where you choose if world command should be run by the player or the console
# Don't worry about this if you're only using the EXTERNAL transfer type
# Options are: "console" and "player"
World-CMD-Mode: "console"

Selector:
  # Choose whether the selector item should be enabled
  Enabled: true

  # Choose what item the server selector should be
  # Default item is Compass (345)
  Item: 345

  # Choose what slot of the player's inventory the selector should appear in
  # The range for this input is 0-35 (0-8 are the player's hotbar)
  Slot: 0

  # This is the text that will show on the selector in the player's inventory
  Name: "§l§aServer Selector"

UI:
  # This is the title of the transfer UI
  Title: "§9Server List"

  # This is the message the will show under your title on the transfer UI
  Message: "§aChoose a server to transfer to!"

  # This is the message displayed under each button 
  Button-Subtext: "§r§o§8Tap to transfer"

# This is where you list your servers or worlds to be displayed on the transfer UI
# You can use '§' and '&' on the labels to style your servers or worlds inside the UI
# For images, use 'url' or 'path' to show an image in the menus (or leave blank to disable)
# NOTE: If you are using a URL, do NOT include the 'https://' or 'http://' in the link!
# If you are using the INTERNAL transfer type, the world name will be taken from the 'WorldTitle' key

# Add as many servers or worlds as you'd like:
# Add SERVERS using this format → ext:ServerTitle:ServerIP:ServerPort:ImageType:Path/URL
# Add WORLDS using this format → int:WorldTitle:WorldAlias:ImageType:Path/URL
List:
  - "ext:§l§2Prison §eServer:play.xenoservers.net:19133:url:i.imgur.com/lLJWjfr.png" # ← EXTERNAL server example
  - "int:§l§5Creative:creative:url:i.imgur.com/8pbNECc.png" # ← INTERNAL world example
